### ISSUE TITLE
bug: The file exists in scripts/golangci.yml, but it still gives an error

### ISSUE THREAD

**Issue by cubxxw** [golangci/golangci-lint-action#832]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

The file exists in scripts/golangci.yml, but it still gives an error, I don't know why, https://github.com/OpenIMSDK/Open-IM-Server/actions/runs/5948295706/job/16131814148?pr=921

```
Run golangci/golangci-lint-action@v3
prepare environment
run golangci-lint
Error: Failed to run: Error: working-directory (server) was not a path, Error: working-directory (server) was not a path
    at runLint (/home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:66817:19)
    at /home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:66849:53
    at Object.<anonymous> (/home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:2057:28)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:1808:71
    at new Promise (<anonymous>)
    at __webpack_modules__.2186.__awaiter (/home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:1804:[12](https://github.com/OpenIMSDK/Open-IM-Server/actions/runs/5948295706/job/16131814148?pr=921#step:4:13))
    at Object.group (/home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:2053:12)
    at run (/home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:66849:20)
    at runMicrotasks (<anonymous>)
Error: working-directory (server) was not a path
```

code:
```
name: OpenIM golangci-lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
    golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v4
          with:
            go-version: '1.21'
            cache: false
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3.7.0
          with:
            # Require: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
            version: v1.53

            # Optional: working directory, useful for monorepos
            working-directory: server

            # Optional: golangci-lint command line arguments.
            # 
            # Note: by default the `.golangci.yml` file should be at the root of the repository.
            # The location of the configuration file can be changed by using `--config=`
            args: --timeout=30m --config=/scripts/golangci.yml  --issues-exit-code=0

            # Optional: show only new issues if it's a pull request. The default value is `false`.
            only-new-issues: true

            # Optional:The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
            install-mode: "binary"
```

### Version of golangci-lint

3.0

### Version of the GitHub Action

no

### Workflow file

<details>

```
<add you file here>
```

</details>

### Go version

1.21

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
>  Error: working-directory (server) was not a path

It's because `working-directory` value is not a path.
