### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by harajara** [golangci/golangci-lint-action#938]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

Getting the below error while running it in github action 

```sh 

Running [/home/runner/golangci-lint-1.54.2-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  panic: runtime error: index out of range [2] with length 2 [recovered]
  	panic: runtime error: index out of range [2] with length 2
  
  goroutine 176 [running]:
  go/types.(*Checker).handleBailout(0xc0049aed20, 0xc00866db18)
  	go/types/check.go:336 +0x88
  panic({0x1093a80?, 0xc000d1ea50?})
  	runtime/panic.go:914 +0x21f
  go/types.(*Checker).arguments(0xc0049aed20, 0xc006869240, 0xc008c1b300, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc008c29d40, ...}, ...)
  	go/types/call.go:648 +0x17a5
  go/types.(*Checker).callExpr(0xc0049aed20, 0xc008c29c80, 0xc006869240)
  	go/types/call.go:302 +0x86d
  go/types.(*Checker).exprInternal(0xc0049aed20, {0x0, 0x0}, 0xc008c29c80, {0x1372510, 0xc006869240?}, {0x0?, 0x0?})
  	go/types/expr.go:1359 +0x1809
  go/types.(*Checker).rawExpr(0xc0049aed20, {0x0, 0x0}, 0xc008c29c80, {0x1372510?, 0xc006869240?}, {0x0?, 0x0?}, 0x0)
  	go/types/expr.go:965 +0x1a5
  go/types.(*Checker).multiExpr(0x20?, {0x1372510?, 0xc006869240}, 0x0)
  	go/types/expr.go:1517 +0x85
  go/types.(*Checker).initVars(0xfab7c0?, {0xc008c047c0?, 0x1, 0x1}, {0xc0064b90c0?, 0x1, 0x1}, {0x0, 0x0})
  	go/types/assignments.go:398 +0x12c
  go/types.(*Checker).shortVarDecl(0xc0049aed20, {0x1369720, 0xc000d1e9f0}, {0xc0064b9080, 0x1, 0xc006843110?}, {0xc0064b90c0?, 0x1, 0x1})
  	go/types/assignments.go:546 +0xbce
  go/types.(*Checker).stmt(0xc0049aed20, 0x0, {0x1371af0?, 0xc006869280?})
  	go/types/stmt.go:476 +0xee5
  go/types.(*Checker).stmtList(0xc0049aed20?, 0x0, {0xc000cc7600?, 0x0?, 0xc0058348c0?})
  	go/types/stmt.go:124 +0x85
  go/types.(*Checker).funcBody(0xc0049aed20, 0xc0046a[23](https://github.com/htrts/materials-module-service/actions/runs/7409670207/job/20160377156#step:4:25)c0, {0xc006816df0?, 0xc000098c80?}, 0xc008b038c0, 0xc006843350, {0x0, 0x0})
  	go/types/stmt.go:44 +0x345
  go/types.(*Checker).funcDecl.func1()
  	go/types/decl.go:826 +0x39
  go/types.(*Checker).processDelayed(0xc0049aed20, 0x0)
  	go/types/check.go:439 +0x15c
  go/types.(*Checker).checkFiles(0xc0049aed20, {0xc00648b720, 0x9, 0x9})
  	go/types/check.go:383 +0x[24](https://github.com/htrts/materials-module-service/actions/runs/7409670207/job/20160377156#step:4:26)5
  go/types.(*Checker).Files(...)
  	go/types/check.go:341
  github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).loadFromSource(0xc00436a060, 0x2)
  	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:159 +0x6ca
  github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).loadWithFacts(0xc00109d000?, 0x43d9ce?)
  	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:[26](https://github.com/htrts/materials-module-service/actions/runs/7409670207/job/20160377156#step:4:28)1 +0x11d
  github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze(0xc00436a060, 0x2, 0xc00430aa20)
  	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:61 +0xe8
  github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyzeRecursive.func1()
  	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:48 +0x199
  sync.(*Once).doSlow(0x0?, 0x2?)
  	sync/once.go:74 +0xbf
  sync.(*Once).Do(...)
  	sync/once.go:65
  github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyzeRecursive(0xc000e7b380?, 0x1379190?, 0xc00136ab10?)
  	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:37 +0x4c
  github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*runner).analyze.func2(0x0?)
  	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:[27](https://github.com/htrts/materials-module-service/actions/runs/7409670207/job/20160377156#step:4:29)4 +0x[28](https://github.com/htrts/materials-module-service/actions/runs/7409670207/job/20160377156#step:4:30)
  created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*runner).analyze in goroutine 1
  	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:273 +0x5c6
  
  Error: golangci-lint exit with code 2
  Ran golangci-lint in 697[66](https://github.com/htrts/materials-module-service/actions/runs/7409670207/job/20160377156#step:4:68)ms
```

### Version of golangci-lint

v1.54.2

### Version of the GitHub Action

v3

### Workflow file

The golangci version is local and github actions remains same. In local, the golangci-lint passes without any error 

```
 GolangLint:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.54.2
```

### Go version

1.21.1

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,

the first version of golangci-lint that supports go 1.21 is v1.55.0.

You have to update your version.
